"""Phase 2, stages 2-3 — website scraping and scraped-text tracking.

Scrape the customer-provided site and (when its registrable domain differs)
the source-provided site for every row, via the shared Postgres-cached
scraper. Each row gets its scraped texts as columns plus a text_quality
verdict — the junk gate that feeds the held customer ask
(spec: phase2-enrichment.md §2-3 + quality gates).
"""

from pathlib import Path

import pandas as pd

from vdl_tools.shared_tools.tools.logger import logger
from vdl_tools.portfolio_comparison.intake.normalize import identity_domain

SCRAPED_BASENAME = "scraped_texts"

# Parked/for-sale pages answer HTTP but carry no org text. Conservative,
# lowercase substrings.
PARKED_MARKERS = [
    "domain is for sale", "this domain is for sale", "buy this domain",
    "domain has been registered", "parked domain", "domain parking",
    "is available for purchase", "hugedomains", "sedo.com",
    "godaddy.com/domainsearch", "this webpage was generated by the domain owner",
]
THIN_TEXT_CHARS = 200


def classify_text_quality(text, num_errors=0) -> str:
    """ok | thin | parked | dead — anything not 'ok' is customer-ask fuel."""
    if text is None or (isinstance(text, float) and text != text) or not str(text).strip():
        return "dead" if num_errors else "empty"
    lowered = str(text).lower()
    if any(marker in lowered for marker in PARKED_MARKERS):
        return "parked"
    if len(str(text).strip()) < THIN_TEXT_CHARS:
        return "thin"
    return "ok"


def select_scrape_targets(acquired: pd.DataFrame) -> pd.DataFrame:
    """Per row: the customer site and the first source site on a DIFFERENT
    registrable domain (nzi -> cb -> gt preference, matching text-objective
    source preference). Platform domains are never scrape targets."""
    rows = []
    for _, row in acquired.iterrows():
        customer_url = row.get("customer_url")
        customer_domain = identity_domain(customer_url) if pd.notna(customer_url) else ""
        source_url = source_domain = None
        for col in ("nzi_website", "cb_website", "gt_website"):
            candidate = row.get(col)
            domain = identity_domain(candidate) if pd.notna(candidate) else ""
            if domain and domain != customer_domain:
                source_url, source_domain = str(candidate), domain
                break
        rows.append({
            "customer_row_id": row["customer_row_id"],
            "customer_scrape_url": str(customer_url) if customer_domain else None,
            "customer_domain": customer_domain or None,
            "source_scrape_url": source_url,
            "source_domain": source_domain,
        })
    return pd.DataFrame(rows)


def _default_scraper(urls: list[str]) -> pd.DataFrame:
    from vdl_tools.scrape_enrich.scraper.scrape_websites import scrape_websites_psql
    from vdl_tools.shared_tools.web_summarization.website_summarization_cache_psql import (
        GENERIC_ORG_WEBSITE_PROMPT_TEXT,
    )

    # Same prompt the summarization stage uses, so the scraper's token
    # budgeting matches what the LLM will actually see.
    return scrape_websites_psql(
        urls,
        summary_prompt=GENERIC_ORG_WEBSITE_PROMPT_TEXT,
        return_combined_res=True,
    )


def scrape_texts(
    acquired: pd.DataFrame,
    results_dir: str | Path,
    scraper=_default_scraper,
) -> pd.DataFrame:
    """Scrape each distinct domain once; fan texts back out to rows."""
    from vdl_tools.scrape_enrich.scraper.scrape_websites import extract_website_name

    targets = select_scrape_targets(acquired)

    url_by_domain: dict[str, str] = {}
    for _, t in targets.iterrows():
        for url_col, dom_col in (("customer_scrape_url", "customer_domain"),
                                 ("source_scrape_url", "source_domain")):
            if t[dom_col] and t[dom_col] not in url_by_domain:
                url_by_domain[t[dom_col]] = t[url_col]

    logger.info("scrape: %d distinct domains across %d rows",
                len(url_by_domain), len(targets))
    scraped = scraper(sorted(url_by_domain.values()))

    by_key: dict[str, dict] = {}
    for _, s in scraped.iterrows():
        n_err = s.get("num_errors")
        by_key[s["cleaned_home_key"]] = {
            "text": s.get("combined_text"),
            "num_errors": int(n_err) if pd.notna(n_err) else 0,
        }

    def _lookup(url):
        if not url:
            return None, 0
        rec = by_key.get(extract_website_name(url))
        return (rec["text"], rec["num_errors"]) if rec else (None, 1)

    # Row verdict = the best verdict any of its sites earned.
    _RANK = {"ok": 0, "thin": 1, "empty": 2, "parked": 3, "dead": 4, "no_url": 5}

    out_rows = []
    for _, t in targets.iterrows():
        cust_text, cust_err = _lookup(t["customer_scrape_url"])
        src_text, src_err = _lookup(t["source_scrape_url"])
        cust_q = (classify_text_quality(cust_text, cust_err)
                  if t["customer_domain"] else "no_url")
        src_q = (classify_text_quality(src_text, src_err)
                 if t["source_domain"] else "no_url")
        out_rows.append({
            "customer_row_id": t["customer_row_id"],
            "customer_domain": t["customer_domain"],
            "source_domain": t["source_domain"],
            "scraped_text_customer_url": cust_text,
            "scraped_text_source_url": src_text,
            "customer_url_quality": cust_q,
            "source_url_quality": src_q,
            "text_quality": min(cust_q, src_q, key=_RANK.__getitem__),
        })
    out = pd.DataFrame(out_rows).astype(object)
    out = out.where(pd.notna(out), pd.NA)

    results_dir = Path(results_dir)
    out.to_parquet(results_dir / f"{SCRAPED_BASENAME}.parquet", index=False)
    out.to_csv(results_dir / f"{SCRAPED_BASENAME}.csv", index=False)
    logger.info("scrape quality: %s",
                out["text_quality"].value_counts(dropna=False).to_dict())
    return out
