[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "vdl_tools/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
]

[tool.hatch.build.targets.wheel]
packages = ["vdl_tools"]

[tool.setuptools.dynamic]
version = {attr = "vdl_tools.__version__"}

[project]
name = "vdl-tools"
dynamic = ["version"]
dependencies = [
    "alembic",
    "awscli",
    "bokeh",
    "boto3",
    "cairosvg",
    "circlify",
    "datasets",
    "dataclasses_json",
    "geopy",
    "geotext",
    "google-auth-oauthlib",
    "google-cloud-translate",
    "google-api-python-client",
    "igraph",
    "instructor",
    "jsonlines",
    "jsonschema",
    "markdown",
    "markdown3-newtab",
    "more-itertools",
    "networkx",
    "nltk",
    "numpy",
    "openai",
    "openpyxl",
    "pandas",
    "plotly",
    "psycopg2-binary",
    "PySocks",
    "pyyaml",
    "regex",
    "requests",
    "requests-cache",
    "scikit-learn",
    "scikit-network",
    "scipy",
    "selenium",
    "sqlalchemy",
    "sqlalchemy-utils",
    "tiktoken",
    "treelib",
    "torch",
    "transformers",
    "umap",
    "url-normalize",
    "webdriver_manager",
    "xlsxwriter",
    "Wikipedia-API",
]
requires-python = ">=3.12"
description = "VDL Tools"
readme = "README.md"

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]