intersectional_fewshot_examples = [
    {
        "entity_description": "350 Seattle is a grassroots organization dedicated to climate justice, focusing on systemic change through various campaigns and projects. They work on resisting fossil fuels, promoting healthy alternatives, and advocating for climate justice, emphasizing collaboration with frontline communities and addressing environmental injustices. The organization supports workers transitioning to clean renewables and advocates for policies that drive ambitious and just climate solutions. Through their efforts, they aim to build a people's movement towards a future with renewable energy, healthy environments, and equitable living for all.",
        "activity_name": "Social Justice",
        "activity_description": "Social Justice acknowledges that climate change disproportionately impacts marginalized and vulnerable communities. Therefore, the fight against climate change is a fight for equality and fairness. This theme spotlights the need for climate policies that center equity, ensuring that those most affected by climate change have a voice in shaping solutions. Climate justice intersects with every solution pathway, insisting that whether we're transforming energy systems or protecting ecosystems, the rights and needs of all people must be front and center.",
        "relevant": True,
    },
    {
        "entity_description": "This organization focuses on addressing the challenges posed by cyanobacterial harmful algal blooms (cyanoHABs) in freshwater systems, particularly the diverse and potent toxins produced during these events. Their work involves identifying and isolating emerging toxic compounds through advanced metabolomics and microbial community analyses, aiming to expand the understanding beyond traditionally studied toxins like microcystins. They conduct comprehensive toxicological assessments using integrated computational, laboratory, and proteomic methods to elucidate the mechanisms of toxin-induced liver injury and systemic effects. By developing new detection and evaluation tools, the organization supports natural resource management and public health policy related to cyanoHABs. Their research advances knowledge of the chemical diversity and toxicity of cyanobacterial metabolites, contributing to improved environmental and health risk assessments.",
        "activity_name": "Algal Bloom Monitoring",
        "activity_description": "Algal Bloom Monitoring: Integrated systems combine multiple technologies to detect, track, and predict harmful algal blooms accelerated by climate-driven changes. The system utilizes Remote Sensing Imagery for early detection and spatial mapping, In-Situ Sensor Networks for real-time, high-frequency localized measurements, and Predictive Modeling with AI to forecast the onset, intensity, and movement of blooms. This provides early warning and predictive capability, enabling timely management responses such as fishery closures, water treatment adjustments, and public health advisories before toxicity peaks and exposure occurs.",
        "relevant": False,
    },
    {
        "entity_description": "This organization focuses on addressing the challenges posed by cyanobacterial harmful algal blooms (cyanoHABs) in freshwater systems, particularly the diverse and potent toxins produced during these events. Their work involves identifying and isolating emerging toxic compounds through advanced metabolomics and microbial community analyses, aiming to expand the understanding beyond traditionally studied toxins like microcystins. They conduct comprehensive toxicological assessments using integrated computational, laboratory, and proteomic methods to elucidate the mechanisms of toxin-induced liver injury and systemic effects. By developing new detection and evaluation tools, the organization supports natural resource management and public health policy related to cyanoHABs. Their research advances knowledge of the chemical diversity and toxicity of cyanobacterial metabolites, contributing to improved environmental and health risk assessments.",
        "activity_name": "Environmental Toxin Testing",
        "activity_description": "Diagnostics & Screening - Environmental Toxin Testing refers to the development and deployment of laboratory and point-of-care technologies for detecting and quantifying harmful environmental toxins in biological samples or through noninvasive means. This includes advanced analytical platforms such as liquid chromatography-mass spectrometry (LC-MS) for precise identification of chemical contaminants, rapid field tests for heavy metals in blood or urine, and portable toxicology screening kits for acute exposures to pesticides, industrial chemicals, or environmental pollutants. Noninvasive detection methods, such as pulse CO-oximetry and breath analysis, enable real-time assessment of carbon monoxide poisoning and other inhaled toxins. Multiplex assays are being advanced to simultaneously detect multiple toxins, including those from waterborne or foodborne sources like fish and shellfish toxins. Emerging innovations include wearable biosensors for continuous monitoring of toxin exposure and miniaturized lab-on-a-chip devices for rapid, on-site diagnostics. These solutions are critical for timely diagnosis and management of acute and chronic health effects resulting from climate-driven increases in toxic exposures, such as wildfires, flooding, and contamination events. Novel approaches under exploration involve AI-driven interpretation of complex toxicology data and integration of environmental exposure data with clinical diagnostics for personalized risk assessment.",
        "relevant": True,
    },
    {
        "entity_description": "Our Climate is an organization dedicated to empowering young people to advocate for science-based, equitable, and intersectional climate justice policies. They engage and mobilize youth leaders to work towards eliminating greenhouse gas pollution and transitioning to a more equitable and regenerative economy. Through structured programs and partnerships, Our Climate trains young leaders to advance climate justice solutions at state and federal levels. They focus on youth engagement, leadership development, and creative civic engagement to achieve systemic change in climate policy.",
        "activity_name": "Youth Leadership",
        "activity_description": "Youth Leadership as an intersectional theme underscores the vital role of youth in climate action. Young people are not just the beneficiaries of a stable climate future—they are actively shaping it. From leading global climate strikes to pioneering green innovations, the youth are redefining what it means to be a climate leader. This theme cuts across all solution pathways, infusing them with urgency, fresh perspective, and unwavering hope",
        "relevant": True,
    },
    {
        "entity_description": "EnFin is a finance company specializing in providing affordable lending solutions for residential solar installations. They collaborate with top solar manufacturers in the United States to offer quick funding and simplify the approval process for both installers and homeowners. EnFin's mission is to empower homeowners to manage their residential energy expenses while supporting the growth of residential solar installers. Through their user-friendly technology and competitive rates, EnFin aims to be a leading lending partner in the solar industry. Visit their website to learn more about their services and partnerships.",
        "activity_name": "Social Justice",
        "activity_description": "Social Justice acknowledges that climate change disproportionately impacts marginalized and vulnerable communities. Therefore, the fight against climate change is a fight for equality and fairness. This theme spotlights the need for climate policies that center equity, ensuring that those most affected by climate change have a voice in shaping solutions. Climate justice intersects with every solution pathway, insisting that whether we're transforming energy systems or protecting ecosystems, the rights and needs of all people must be front and center.",
        "relevant": False,
    },
    {
        "entity_description": "The Colorado-Wyoming Climate Resilience Engine is a pioneering initiative focused on sustainability and environmental consulting. Through the development of climate-resilient technologies, the organization addresses pressing challenges like wildfire mitigation and water resource management. By fostering inclusivity and workforce development, the CO-WY Engine aims to drive economic growth and position the region as a leader in sustainable practices. Partnering with federal laboratories, research universities, and industry stakeholders, the organization is dedicated to advancing innovation and promoting resilience in the face of climate change.",
        "activity_name": "Youth Leadership",
        "activity_description": "Youth Leadership as an intersectional theme underscores the vital role of youth in climate action. Young people are not just the beneficiaries of a stable climate future—they are actively shaping it. From leading global climate strikes to pioneering green innovations, the youth are redefining what it means to be a climate leader. This theme cuts across all solution pathways, infusing them with urgency, fresh perspective, and unwavering hope",
        "relevant": False,
    },
    {
        "entity_description": "Triangle is a pioneering organization at the intersection of climate and finance, offering innovative solutions for climate compliance in sectors such as CleanTech, Agriculture, Financial Services, and more. Their AssetOS platform leverages big data sources to create digital twins of assets, enabling efficient tracking of sustainability metrics and climate performance. By providing tools for TCFD compliance, Sustainability-linked Underwriting, and Carbon Credit Minting, Triangle empowers banks, asset managers, and governments to navigate climate regulations while reducing borrowing costs. With a focus on delivering scalable solutions for climate resilience, Triangle is driving impactful change in the realms of sustainability and infrastructure.",
        "activity_name": "Climate Finance",
        "activity_description": "Climate Finance refers to the mobilization of both governmental and private sector financial resources to fund and rapidly scale climate solutions. Examples include government grants, private investments, and public-private partnerships.",
        "relevant": True,
    },
]

falsesolns_fewshot_examples = [
    {
        "entity_description": "Oklo is dedicated to advancing clean energy solutions through the development of next-generation fission reactors. The organization focuses on producing reliable and affordable energy while utilizing recycled nuclear waste, significantly reducing carbon emissions. With a commitment to innovation and safety, Oklo aims to transform the energy landscape by deploying advanced fission technology on a global scale. Their efforts are supported by a diverse team with expertise across multiple industries, positioning Oklo as a leader in the clean energy sector.",
        "activity_name": "Nuclear Fission (Conventional)",
        "activity_description": "Conventional nuclear fission is a process used in nuclear reactors where the nucleus of an atom, typically uranium or plutonium, is split into smaller nuclei by bombarding it with neutrons. This splitting releases a significant amount of energy in the form of heat and radiation. The heat produced is usually used to generate steam, which drives turbines to produce electricity.",
        "relevant": True,
    },
    {
        "entity_description": "Our Climate is an organization dedicated to empowering young people to advocate for science-based, equitable, and intersectional climate justice policies. They engage and mobilize youth leaders to work towards eliminating greenhouse gas pollution and transitioning to a more equitable and regenerative economy. Through structured programs and partnerships, Our Climate trains young leaders to advance climate justice solutions at state and federal levels. They focus on youth engagement, leadership development, and creative civic engagement to achieve systemic change in climate policy.",
        "activity_name": "Nuclear Fission (Conventional)",
        "activity_description": "Conventional nuclear fission is a process used in nuclear reactors where the nucleus of an atom, typically uranium or plutonium, is split into smaller nuclei by bombarding it with neutrons. This splitting releases a significant amount of energy in the form of heat and radiation. The heat produced is usually used to generate steam, which drives turbines to produce electricity.",
        "relevant": False,
    },
    {
        "entity_description": "EnFin is a finance company specializing in providing affordable lending solutions for residential solar installations. They collaborate with top solar manufacturers in the United States to offer quick funding and simplify the approval process for both installers and homeowners. EnFin's mission is to empower homeowners to manage their residential energy expenses while supporting the growth of residential solar installers. Through their user-friendly technology and competitive rates, EnFin aims to be a leading lending partner in the solar industry. Visit their website to learn more about their services and partnerships.",
        "activity_name": "Geoengineering",
        "activity_description": "Geoengineering refers to large-scale technological interventions in the Earth’s climate system intended to counteract global warming. These approaches do not address the root causes of climate change and pose significant risks to ecosystems, weather patterns, and global governance. Rather than reducing greenhouse gas emissions, geoengineering attempts to artificially manipulate planetary systems, often with unpredictable and potentially harmful consequences.",
        "relevant": False,
    },
    {
        "entity_description": "Make Sunsets is an organization focused on addressing climate change through a technique known as stratospheric aerosol injection (SAI). This method involves deploying reflective particles into the stratosphere using balloons, which creates a thin layer that reflects some of the Sun's rays, thereby reducing the amount of heat that reaches the Earth's surface. The organization draws inspiration from the natural cooling effects observed during volcanic eruptions. Each gram of these reflective particles is estimated to offset the warming effect of one ton of carbon dioxide for a year.Make Sunsets advocates for a multi-faceted approach to combat climate change, emphasizing the urgency of immediate action to mitigate the effects of global warming. They highlight the limitations of traditional methods such as carbon offsets and renewable energy, arguing that SAI can provide a more immediate solution to prevent further temperature increases. The organization actively conducts balloon launches to deploy their reflective clouds and collects data on these deployments to support their scientific research and initiatives.",
        "activity_name": "Geoengineering: Stratospheric Aerosol Injection",
        "activity_description": "Geoengineering: Stratospheric Aerosol Injection: This involves releasing sulfate aerosols or other reflective particles into the stratosphere to reflect sunlight away from Earth, mimicking the cooling effect of large volcanic eruptions.",
        "relevant": True,
    },
    {
        "entity_description": "tH2 Power is dedicated to advancing modular carbon capture technologies tailored for natural gas processing and treatment facilities. The organization is committed to promoting sustainable energy solutions, including the production of clean ammonia and metallurgical grade silicon through innovative systems powered by clean hydrogen. By focusing on these initiatives, tH2 Power aims to stimulate local economic growth and create high-income job opportunities in the communities it serves. Their efforts are designed to foster economic recovery and support environmental sustainability in the regions they operate.",
        "activity_name": "Carbon capture & storage (CCS): Pre-combustion Capture",
        "activity_description": "Carbon capture & storage (CCS): Pre-combustion Capture: Involves converting fossil fuels into a gaseous mixture of hydrogen and carbon dioxide before combustion. The CO2 is separated out from this gas mixture, typically at high pressures.",
        "relevant": True,
    },
]


intersectional_true_examples = [
    {
        "entity_description": "350 Seattle is a grassroots organization dedicated to climate justice, focusing on systemic change through various campaigns and projects. They work on resisting fossil fuels, promoting healthy alternatives, and advocating for climate justice, emphasizing collaboration with frontline communities and addressing environmental injustices. The organization supports workers transitioning to clean renewables and advocates for policies that drive ambitious and just climate solutions. Through their efforts, they aim to build a people's movement towards a future with renewable energy, healthy environments, and equitable living for all.",
        "activity_name": "Social Justice",
        "activity_description": "Social Justice acknowledges that climate change disproportionately impacts marginalized and vulnerable communities. Therefore, the fight against climate change is a fight for equality and fairness. This theme spotlights the need for climate policies that center equity, ensuring that those most affected by climate change have a voice in shaping solutions. Climate justice intersects with every solution pathway, insisting that whether we're transforming energy systems or protecting ecosystems, the rights and needs of all people must be front and center.",
        "relevant": True,
    },
    {
        "entity_description": "Our Climate is an organization dedicated to empowering young people to advocate for science-based, equitable, and intersectional climate justice policies. They engage and mobilize youth leaders to work towards eliminating greenhouse gas pollution and transitioning to a more equitable and regenerative economy. Through structured programs and partnerships, Our Climate trains young leaders to advance climate justice solutions at state and federal levels. They focus on youth engagement, leadership development, and creative civic engagement to achieve systemic change in climate policy.",
        "activity_name": "Youth Leadership",
        "activity_description": "Youth Leadership as an intersectional theme underscores the vital role of youth in climate action. Young people are not just the beneficiaries of a stable climate future—they are actively shaping it. From leading global climate strikes to pioneering green innovations, the youth are redefining what it means to be a climate leader. This theme cuts across all solution pathways, infusing them with urgency, fresh perspective, and unwavering hope",
        "relevant": True,
    },
    {
        "entity_description": "Triangle is a pioneering organization at the intersection of climate and finance, offering innovative solutions for climate compliance in sectors such as CleanTech, Agriculture, Financial Services, and more. Their AssetOS platform leverages big data sources to create digital twins of assets, enabling efficient tracking of sustainability metrics and climate performance. By providing tools for TCFD compliance, Sustainability-linked Underwriting, and Carbon Credit Minting, Triangle empowers banks, asset managers, and governments to navigate climate regulations while reducing borrowing costs. With a focus on delivering scalable solutions for climate resilience, Triangle is driving impactful change in the realms of sustainability and infrastructure.",
        "activity_name": "Climate Finance",
        "activity_description": "Climate Finance refers to the mobilization of both governmental and private sector financial resources to fund and rapidly scale climate solutions. Examples include government grants, private investments, and public-private partnerships.",
        "relevant": True,
    },
    {
        "entity_description": "Impossible Mining is a pioneering organization specializing in responsible seabed mining for critical battery metals. Their innovative underwater robotics vehicles and cutting-edge mineral processing techniques prioritize environmental preservation while meeting the demands of a transitioning energy landscape. Committed to sustainable practices and supporting global sustainability goals, Impossible Mining is at the forefront of advancing clean energy technologies. Established in 2020 in Pasadena, California, the company's core values emphasize environmental stewardship, innovation, and continuous learning.",
        "activity_name": "Science & Technology refers to scientific research and technological innovation developing novel climate solutions and providing decision-makers at all levels with the tools and knowledge they need to prioritize implementing the best climate solutions. Examples include projects narrowly-focused on developing new technologies to address a single climate mitigation or adaptation problem and efforts developing science-based roadmaps broadly addressing climate solutions.",
        "activity_description": "Science & Technology",
        "relevant": True,
    },
    {
        "entity_description": "The Coral Reef Research Foundation (CRRF) is a non-profit organization dedicated to marine research and education, with a focus on coral reefs and tropical marine environments. Established in 1991, CRRF conducts original research in Palau and beyond, covering topics such as conservation decisions, species diversity, climate change monitoring, and marine ecosystems. Their research programs aim to enhance public awareness and management recommendations through biology and ecology studies, while collaborating with visiting scientists and maintaining an online data archive. CRRF operates a waterfront marine research facility in Palau, equipped with lab space, accommodation, and research boats, to support their studies on marine organisms and environments.",
        "activity_name": "Biological Diversity",
        "activity_description": "Biological Diversity emphasizes the vital importance of protecting the Earth's vast array of life. This theme champions the interconnectedness of all living things, recognizing that the health of our planet is dependent on the richness of its biodiversity. From conserving our forests to protecting endangered species, this theme intertwines with all solution pathways, reminding us that every climate solution is, at its heart, a solution that respects and protects the web of life.",
        "relevant": True,
    },
]


harpah_examples = [
    {
        "entity_description": "Alexium International is a performance chemicals company specializing in advanced materials focused on thermal regulation and flame retardant solutions. Their innovative technologies include microencapsulated phase-change materials and other proprietary treatments designed to enhance cooling performance and fire safety. These high-performance products are applied across various industries, including bedding, military uniforms, body armor, and workwear. Alexium’s solutions are customizable to meet specific customer requirements, addressing challenges related to thermal comfort and flame retardancy.",
        "activity_name": "Personal Cooling Tech",
        "activity_description": "Personal Cooling Tech: Active cooling garments, vests, or neckwear using phase-change materials or battery-powered fans to lower skin temperature during outdoor activity.",
        "relevant": True,
    },
    {
        "entity_description": "Aquaria is a Public Benefit Corporation focused on providing clean, reliable water by generating it directly from atmospheric moisture. Their technology, embedded in a range of atmospheric water generators (AWGs), produces fresh water by extracting and filtering water vapor from the air, delivering water that meets or exceeds EPA and WHO quality standards. Aquaria offers scalable solutions suitable for individual households, communities, and commercial applications, with products capable of producing from around 24 gallons to over 5,000 gallons per day. These systems can operate independently or integrate with existing water sources and storage, and can be powered by various energy sources including solar. The company aims to address water scarcity by enabling water independence, particularly in areas lacking traditional water infrastructure, and has deployed its technology to serve thousands of people across more than 30 countries. Aquaria emphasizes social responsibility, customer empowerment, and sustainability, with a goal to provide water access to one million people within the next decade while reducing plastic waste.",
        "activity_name": "Atmospheric Water Generation",
        "activity_description": "Atmospheric Water Generation: Devices that extract potable water from humidity in the air, providing a decentralized, off-grid water source during scarcity.",
        "relevant": True,
    },
    {
        "entity_description": "Evigence is an organization focused on enhancing the freshness management of food products throughout the supply chain. Their Freshness Management Platform integrates sensors and data analytics to provide real-time monitoring of food freshness from production to consumption. This technology is particularly relevant in addressing the challenges posed by temperature fluctuations and time exposure, which can significantly impact the shelf life and safety of perishable goods. The company, which holds 27 patents, originally specialized in healthcare technology for vaccine monitoring before transitioning to the food sector in 2016. Evigence's sensors, known as time-temperature indicators (TTIs), track cumulative time and temperature exposure, offering insights that help optimize freshness and reduce food waste. Their solutions are designed to provide visibility and traceability for food brands, retailers, and foodservice providers, ensuring compliance with food safety standards.",
        "activity_name": "Smart Cold Chain Monitoring",
        "activity_description": "Smart Cold Chain Monitoring: IoT sensors that track temperature and humidity of food shipments continuously, alerting logistics providers to breaches that could cause spoilage.",
        "relevant": True,
    },
    {
        "entity_description": "This organization focuses on addressing groundwater contamination by arsenic, particularly in vulnerable delta regions of South and Southeast Asia. Their work integrates multiple disciplines including hydrogeology, geochemistry, remote sensing, and data science to understand the spatial and temporal patterns of arsenic contamination and its driving factors. They develop advanced modeling techniques, such as interpretable machine learning and reactive transport models, to predict contamination changes over decadal timescales and assess the impact of anthropogenic and environmental disturbances. Their research aims to inform water resource management and policy decisions, ultimately supporting the development of effective mitigation strategies to ensure safe water supplies for growing populations in affected regions.",
        "activity_name": "Contaminant Plume Modeling",
        "activity_description": "Contaminant Plume Modeling: Software that uses hydrological data to predict the movement of underground contaminant plumes as water tables rise, guiding remediation efforts.",
        "relevant": True,
    },
    {
        "entity_description": "American Water is the largest regulated water and wastewater utility company in the United States, providing safe, clean, reliable, and affordable services to millions of people across multiple states and military installations. The company focuses on infrastructure investment, system resiliency, and regulated acquisitions to support sustainable water management. It emphasizes safety, environmental protection, affordability, and customer service while fostering an inclusive workforce and strong community partnerships. American Water leverages its national scale and expertise to deliver consistent, high-quality water and wastewater solutions.",
        "activity_name": "Smart Water-Quality Sensor Networks",
        "activity_description": "Smart Water-Quality Sensor Networks: Distributed networks of sensors installed in rivers, reservoirs, wells, storage tanks and distribution pipes that continuously measure parameters such as turbidity, conductivity, salinity, temperature, residual disinfectant, nutrients and microbial proxies. Data are transmitted in real time to analytics platforms that flag contamination events, guide flushing or switching to alternative sources and support advisories to prevent consumption of unsafe water.",
        "relevant": False,
    },
    {
        "entity_description": "This organization focuses on advancing skin health by developing innovative methods to evaluate the safety and effectiveness of chemical UV filters used in sunscreens. They employ high-throughput screening platforms that utilize cultured human skin cells to assess DNA damage and cellular responses to ultraviolet radiation in the presence of various sunscreen ingredients. Their work integrates cutting-edge technologies such as CRISPR gene editing, 3D skin models, and artificial intelligence to enhance the accuracy and relevance of their testing. By providing these services, they aim to support early-stage drug discovery, regulatory evaluation, and formulation optimization for safer and more effective sun protection products. Their efforts address critical public health concerns related to skin cancer and the limitations of current sunscreen formulations.",
        "activity_name": "Dermal Barriers for Particulates",
        "activity_description": "Dermal Barriers for Particulates: Advanced topical formulations and mineral-based barrier agents designed to block the transdermal absorption of environmental toxins. These barriers form a microscopic physical shield on the skin to prevent contact dermatitis and systemic toxicity from wildfire ash, heavy-metal-laden drought dust, and fungal spores, often integrated with broad-spectrum UV protection for degraded atmospheric conditions.",
        "relevant": False,
    },

    ]

lstudio_examples = [
    {
        "entity_description": "Chesapeake Bay Academy is an educational institution focused on providing individualized instruction to students with diverse learning differences, including dyslexia, ADHD, and other cognitive challenges. The academy emphasizes a personalized approach through Individualized Instructional Plans (IIPs) that cater to each student's unique strengths and needs. With small class sizes and a multisensory curriculum, the school aims to foster academic success and personal growth.The curriculum at Chesapeake Bay Academy includes project-based learning, social-emotional learning, and a variety of extracurricular activities such as intramural athletics and arts programs. The facility is designed to create a supportive and engaging learning environment, featuring specialized classrooms equipped with technology and resources tailored to the needs of exceptional learners.Chesapeake Bay Academy's mission is to empower students with the skills and confidence necessary for success in higher education and life, while its vision promotes an inclusive educational environment that values diversity. The academy is committed to continuous improvement and the individual success of its students, ensuring that each child is recognized for their unique contributions.",
        "activity_name": "Supports for Learning Differences",
        "activity_description": "Supports for Learning Differences: Instructional models and specialized environments designed for students with specific cognitive, linguistic, or physical needs (Neurodiversity). This category encompasses both the specialized infrastructure (IEP software, assistive tech) and the specialized educational institutions where the entire curriculum and facility are adapted to the learner’s unique neurodivergent profile. An organization qualifies if they serve neurodivergent learners (Dyslexia, ADHD, Autism, 2e). What Orgs/Companies Offer: Specialized Learning Environments: Private or laboratory schools dedicated exclusively to neurodiverse students (e.g., Chesapeake Bay Academy). Adaptive Infrastructure: IEP/IIP management software and data tools for MTSS tracking. Assistive Technologies: Speech-to-text, eye-tracking, and sensory-friendly classroom hardware (e.g., non-flicker lighting, acoustical dampening). Linguistic Supports: Translation, ESL/ELL software, and research-based literacy interventions (e.g., Orton-Gillingham based tools). Exclusionary Rule: Strictly excludes general-population schools that merely offer 'resource rooms' or standard IEP accommodations. The focus must be on specialized, neurodiversity-first models.",
        "relevant":True,
    },
    {
        "entity_description": "The Center for Collaborative Education (CCE) is an organization focused on enhancing educational outcomes and empowering communities through collaborative partnerships. Established in 1994, CCE aims to transform traditional education models by fostering strong connections between schools and the communities they serve. The organization emphasizes the importance of community involvement in education, believing that such engagement leads to improved student success and community well-being.CCE's initiatives include developing educator pathways that prioritize community-driven educators, promoting reciprocity between schools and communities, and creating apprenticeship programs that connect education with real-world career opportunities. Their approach is centered on recognizing the unique needs and strengths of both students and communities, aiming to cultivate well-rounded graduates who thrive academically, personally, socially, and emotionally.Through innovative programs and a dedicated team, CCE seeks to replace conventional educational frameworks with more inclusive and effective strategies that support the diverse needs of students and their communities.",
        "activity_name":"Collective Problem-Solving",
        "activity_description":"Collective Problem-Solving: This category focuses on tapping into the Collective Intelligence of a community—teachers, students, parents, and experts—to solve specific challenges that a single central office cannot solve alone. It moves beyond traditional 'top-down' planning to Community Co-design, where those closest to the problem are the ones building the solutions. It serves as the Crowdsourcing Engine, using open challenges and collaborative platforms to gather, test, and spread the best ideas from every corner of the system. What Orgs/Companies Offer: They provide Open Innovation Platforms, community co-design workshops, and 'Challenge Prizes' (like X-Prizes for education). These organizations offer the tools to host 'Hackathons' for teachers to solve scheduling issues, or 'Design Sprints' where parents and students help redesign the school's approach to safety. They act as the facilitators who turn raw community input into actionable, scalable plans. Identity & Mission Vernacular: 'Community Co-design,' 'Open Innovation,' 'Crowdsourced Solutions', and 'Collaborative Problem-Solving.' Keywords: Hackathons, Design Challenges, Crowdsourcing, Co-creation, Stakeholder Design, and Open-Source Innovation. Exclusionary Rule: Strictly excludes standard 'Public Comment' periods at board meetings (which is Governance) and individual teacher planning (which is Instruction).",
        "relevant": True,
    },
    {
        "entity_description": "Cathedral High School is a Catholic educational institution located in Indianapolis, Indiana, founded in 1918. The school emphasizes the holistic development of its students, integrating academic excellence with spiritual, emotional, and social growth. Cathedral offers a diverse curriculum that includes academics, athletics, and arts, fostering a supportive environment for personal achievement. The school is part of a network of Holy Cross high schools and is committed to inclusivity and diversity, encouraging student participation in various clubs and initiatives that promote understanding and community engagement.With a strong alumni network of over 14,000 members, Cathedral graduates have made significant contributions across various fields, including business, government, and the arts. The school also prioritizes counseling and support services, ensuring that students receive guidance throughout their academic journey. Cathedral High School aims to empower students to achieve their potential and actively participate in their communities, preparing them for future leadership roles.",
        "activity_name": "Traditional Schools",
        "activity_description": "Traditional Schools:  This modality encompasses the full spectrum of campus-based learning, from Early Childhood Education (Birth–Age 5) through Elementary, Middle, and High School. It includes public, private, and Mission-Driven or Values-Based institutions that operate within a structured, community-centered framework. These schools are defined by a commitment to Academic Excellence, Social-Emotional Development, and Holistic Student Growth. They provide a consistent, structured environment where dedicated educators guide learners through a curriculum designed for developmental readiness, grade-level mastery, and future success. This category explicitly includes faith-based/religious schools, pre-K programs, and early childhood education centers. How They Describe Themselves: They identify as Nurturing Learning Communities, College Preparatory Academies, Community Schools, and Early Childhood Centers of Excellence. Their missions focus on nurturing the whole child, inspiring a lifelong love for learning, cultivating strong character, and empowering students to reach their full potential within a safe, supportive, and disciplined environment.Keywords: Pre-K & Early Ed, K-12 Academics, Whole-Child Development, Foundational Literacy, College & Career Readiness, Values-Based Education, Community Traditions, and Parent-Teacher Partnerships. Exclusionary Rule: Strictly excludes schools where the primary operating model is pacing-independent (Competency-Based), location-independent (Purely Virtual/Nomadic), or age-agnostic (Multi-age Houses or Microschools). It also excludes Specialized Modalities that lead with a specific alternative pedagogy (e.g., Montessori, Waldorf, Reggio Emilia) as their primary brand or purely custodial daycare lacking an educational curriculum.",
        "relevant": True,
    },
    {
        "entity_description": "Central Inventions is a research and development organization focused on enhancing online education through learner-centric pedagogy. The organization specializes in creating and optimizing educational software, particularly through its product, Stackmaps, which allows learners to navigate educational materials effectively. Central Inventions collaborates with stakeholders to understand user demographics and learning objectives before developing new learning modules. They emphasize the importance of continuous improvement in education, particularly in response to the growing trend of remote learning and work. Their mission is to foster challenge-seeking behavior, promote talent development, and maximize learning outcomes for innovative organizations.",
        "activity_name":"Prototyping & Incubation",
        "activity_description": "Prototyping & Incubation: Organizations where new educational concepts—ranging from digital tools to pedagogical models and school designs—are nurtured from raw ideas into functional, pilot-ready solutions. This category focuses on Design Thinking and rapid feedback loops, providing a 'sandbox' for educators and entrepreneurs to test 'minimum viable products' (MVPs) in real-world settings. What Orgs/Companies Offer: They provide Innovation Accelerators, 'Model School' incubators, and rapid-prototyping workshops. These organizations offer mentorship, seed funding, and access to Lab Schools where they can test non-tech innovations (like new grading rubrics or flexible seating) alongside digital tools (like AI tutors). They facilitate design sprints that gather feedback from students and teachers to refine a solution’s usability before it is scaled.Identity & Mission Vernacular: K-12 Design Labs, Incubation Hubs, Pilot-to-Scale Accelerators, and Iterative School Design. Keywords: Design Sprints, MVP Development, Pilot Testing, Rapid Iteration, Sandbox Environments, and User-Centered Design.Exclusionary Rule: Strictly excludes long-term academic studies without a build-and-test component and the maintenance of established, static curriculum.",
        "relevant": False,
    }
    ]