"""Scraped-text quality verdicts — the junk gate for scraper output.

Classifies a scrape result before it feeds summarization or classification:
a parked domain answers HTTP and yields text, but the text describes the
registrar, not the org. Origin: the portfolio-comparison pilot, where
"scrape succeeded" and "text is usable" turned out to be different facts.

Every verdict here except "ok" and "thin" means the LLM should never see the
text: summarize_scraped_df skips these classes before spending a call on
them, because a summarizer asked to describe junk does not reliably say so —
it sometimes invents a plausible description from the organization's name
instead. A squatted domain, a bot wall and binary mojibake all produced
fabricated summaries before this module was consulted at the summarize step.
"""

# Parked/for-sale pages answer HTTP but carry no org text. Conservative,
# lowercase substrings. Includes marketplace brand names (squadhelp, afternic,
# expireddomains, dan.com) alongside the generic for-sale phrasing, since a
# marketplace's own copy rarely uses the word "sale".
PARKED_MARKERS = [
    "domain is for sale", "this domain is for sale", "buy this domain",
    "domain has been registered", "parked domain", "domain parking",
    "is available for purchase", "hugedomains", "sedo.com",
    "godaddy.com/domainsearch", "this webpage was generated by the domain owner",
    "domains for sale", "domain marketplace", "squadhelp", "premium domain",
    "brandable domain", "make an offer on this domain", "afternic", "dan.com",
    "expireddomains",
]
THIN_TEXT_CHARS = 200

# Above this share of control characters the scrape returned binary, not text.
# The distribution is bimodal — real pages sit near zero — so the threshold is
# not delicate. Type case: an HTTP 200 with 0 recorded errors and ~1,000 chars
# of mojibake, which a summarizer faithfully described as "corrupted" — and,
# on other pages in the same shape, did not: it invented a description from
# the organization's name instead.
GARBLED_RATIO = 0.02

# Challenge and permission screens. A bot wall answers HTTP 200 and yields
# text, so "scrape succeeded" and "extraction succeeded" are both true and the
# wall gets stored as the page — the same trap as a parked domain, one layer
# further in.
BOT_WALL_MARKERS = [
    "403 - forbidden", "access to this page is forbidden", "access denied",
    "permission to access", "security service to protect against malicious bots",
    "checking your browser", "verify you are human", "enable javascript and cookies",
    "captcha", "ddos protection", "cloudflare", "are you a robot",
    "request unsuccessful",
]
# Wall bodies are short; a real page *discussing* Cloudflare or CAPTCHAs is
# not. Measured over the marker-containing pages of a 24k-domain corpus: under
# 1,000 characters every sampled hit was a wall, over 5,000 every one was a
# real page (a 163KB nonprofit site, a 19KB page whose footer carries a
# reCAPTCHA notice). The 1,000-5,000 band is mixed, so the threshold sits at
# the conservative end of it.
WALL_MAX_CHARS = 1000


def looks_like_garbled_text(text) -> bool:
    """Whether ``text`` is binary/mojibake rather than real page content."""
    if text is None or (isinstance(text, float) and text != text):
        return False
    stripped = str(text).strip()
    if not stripped:
        return False
    control = sum(1 for c in stripped if ord(c) < 32 and c not in "\n\r\t")
    return control / len(stripped) > GARBLED_RATIO


def looks_like_bot_wall(text) -> bool:
    """Whether ``text`` is a challenge screen rather than the site's own page.

    A pure predicate, reused two ways: ``scrape_websites`` calls it directly
    to decide whether a page is worth retrying through the browser, and
    ``classify_text_quality`` composes it into the ``"blocked"`` verdict
    below. Kept separate from that composition because the retry decision has
    to run before a verdict exists at all — the wall may still be fixable.
    """
    if text is None or (isinstance(text, float) and text != text):
        return False
    stripped = str(text).strip()
    if not stripped or len(stripped) >= WALL_MAX_CHARS:
        return False
    lowered = stripped.lower()
    return any(marker in lowered for marker in BOT_WALL_MARKERS)


def classify_text_quality(text, num_errors: int = 0) -> str:
    """ok | thin | parked | blocked | garbled | dead | empty.

    Anything not "ok" or "thin" needs a human, a re-scrape, or a better source
    before the text feeds an LLM.
    """
    if text is None or (isinstance(text, float) and text != text) or not str(text).strip():
        return "dead" if num_errors else "empty"
    stripped = str(text).strip()
    if looks_like_garbled_text(stripped):
        return "garbled"
    if any(marker in stripped.lower() for marker in PARKED_MARKERS):
        return "parked"
    if looks_like_bot_wall(stripped):
        return "blocked"
    if len(stripped) < THIN_TEXT_CHARS:
        return "thin"
    return "ok"
