"""Scraped-text quality verdicts — the junk gate for scraper output.

Classifies a scrape result before it feeds summarization or classification:
a parked domain answers HTTP and yields text, but the text describes the
registrar, not the org. Origin: the portfolio-comparison pilot, where
"scrape succeeded" and "text is usable" turned out to be different facts.
"""

# Parked/for-sale pages answer HTTP but carry no org text. Conservative,
# lowercase substrings.
PARKED_MARKERS = [
    "domain is for sale", "this domain is for sale", "buy this domain",
    "domain has been registered", "parked domain", "domain parking",
    "is available for purchase", "hugedomains", "sedo.com",
    "godaddy.com/domainsearch", "this webpage was generated by the domain owner",
]
THIN_TEXT_CHARS = 200


def classify_text_quality(text, num_errors: int = 0) -> str:
    """ok | thin | parked | dead | empty — anything not 'ok' needs a human
    or a better source before the text feeds an LLM."""
    if text is None or (isinstance(text, float) and text != text) or not str(text).strip():
        return "dead" if num_errors else "empty"
    lowered = str(text).lower()
    if any(marker in lowered for marker in PARKED_MARKERS):
        return "parked"
    if len(str(text).strip()) < THIN_TEXT_CHARS:
        return "thin"
    return "ok"
