import datetime
from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, JSON
from sqlalchemy.dialects.postgresql import JSONB

from vdl_tools.shared_tools.database_cache.database_models.base import Base

class CbOrganization(Base):
    __tablename__ = "cb_organizations"

    identifier = Column(JSONB, nullable=False)  # Crunchbase entity identifier (dict); uuid is the ORM PK (JSONB cannot be PK in SQLAlchemy)
    uuid = Column(String, primary_key=True)
    permalink = Column(String)
    name = Column(String)
    status = Column(String)
    description = Column(String)
    categories = Column(JSONB)
    location_identifiers = Column(JSONB)
    short_description = Column(String)
    founder_identifiers = Column(JSONB)
    website_url = Column(String)
    linkedin = Column(JSONB)
    founded_on = Column(JSONB)
    last_funding_at = Column(String)
    funding_total = Column(JSONB)
    location_group_identifiers = Column(JSONB)
    revenue_range = Column(String)
    operating_status = Column(String)
    company_type = Column(String)
    category_groups = Column(JSONB)
    num_employees_enum = Column(String)
    last_funding_total = Column(JSONB)
    num_funding_rounds = Column(Integer)
    funding_stage = Column(String)
    ipo_status = Column(String)
    last_funding_type = Column(String)
    investor_identifiers = Column(JSONB)
    num_investors = Column(Integer)
    acquirer_identifier = Column(JSONB)
    equity_funding_total = Column(JSONB)
    diversity_spotlights = Column(JSONB)

    aliases = Column(JSONB)
    closed_on = Column(JSONB)
    contact_email = Column(String)
    delisted_on = Column(JSONB)
    demo_days = Column(Boolean)
    entity_def_id = Column(String)
    exited_on = Column(JSONB)
    facebook = Column(JSONB)
    facet_ids = Column(JSONB)
    funds_total = Column(JSONB)
    hub_tags = Column(JSONB)
    image_id = Column(String)
    image_url = Column(String)
    investor_stage = Column(JSONB)
    investor_type = Column(JSONB)
    last_equity_funding_total = Column(JSONB)
    last_equity_funding_type = Column(String)
    legal_name = Column(String)
    listed_stock_symbol = Column(String)
    num_acquisitions = Column(Integer)
    num_alumni = Column(Integer)
    num_articles = Column(Integer)
    num_current_advisor_positions = Column(Integer)
    num_current_positions = Column(Integer)
    num_diversity_spotlight_investments = Column(Integer)
    num_enrollments = Column(String)
    num_event_appearances = Column(Integer)
    num_exits = Column(Integer)
    num_exits_ipo = Column(Integer)
    num_founder_alumni = Column(Integer)
    num_founders = Column(Integer)
    num_funds = Column(Integer)
    num_investments = Column(Integer)
    num_lead_investments = Column(Integer)
    num_lead_investors = Column(Integer)
    num_past_positions = Column(Integer)
    num_portfolio_organizations = Column(Integer)
    num_sub_organizations = Column(Integer)
    owner_identifier = Column(JSONB)
    permalink_aliases = Column(JSONB)
    phone_number = Column(String)
    program_application_deadline = Column(String)
    program_duration = Column(String)
    program_type = Column(String)
    rank_delta_d30 = Column(Integer)
    rank_delta_d7 = Column(Integer)
    rank_delta_d90 = Column(Integer)
    rank_org = Column(Integer)
    rank_principal = Column(Integer)
    school_method = Column(String)
    school_program = Column(String)
    school_type = Column(String)
    stock_exchange_symbol = Column(String)
    stock_symbol = Column(JSONB)
    twitter = Column(JSONB)
    valuation = Column(JSONB)
    valuation_date = Column(String)
    went_public_on = Column(JSONB)

    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class CbFundingRound(Base):
    __tablename__ = "cb_funding_rounds"

    uuid = Column(String, primary_key=True)
    name = Column(String)
    funded_organization_identifier = Column(JSONB)
    money_raised = Column(JSONB)
    announced_on = Column(JSONB)
    lead_investor_identifiers = Column(JSONB)
    investor_identifiers = Column(JSONB)
    investment_stage = Column(String)
    funded_organization_funding_stage = Column(String)
    investment_type = Column(String)
    identifier = Column(JSONB)
    closed_on = Column(JSONB)
    funded_organization_categories = Column(JSONB)
    funded_organization_description = Column(String)
    funded_organization_diversity_spotlights = Column(JSONB)
    funded_organization_funding_total = Column(JSONB)
    funded_organization_location = Column(JSONB)
    funded_organization_revenue_range = Column(String)
    is_equity = Column(Boolean)
    num_investors = Column(Integer)
    num_partners = Column(Integer)
    permalink = Column(String)
    post_money_valuation = Column(JSONB)
    pre_money_valuation = Column(JSONB)
    rank_funding_round = Column(Integer)
    short_description = Column(String)
    target_money_raised = Column(JSONB)

    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class CbPerson(Base):
    __tablename__ = "cb_people"

    uuid = Column(String, primary_key=True)
    name = Column(String)
    aliases = Column(JSONB)
    born_on = Column(JSONB)
    created_at = Column(DateTime)
    description = Column(String)
    died_on = Column(JSONB)
    entity_def_id = Column(String)
    facebook = Column(JSONB)
    facet_ids = Column(JSONB)
    first_name = Column(String)
    gender = Column(String)
    identifier = Column(JSONB)
    image_id = Column(String)
    image_url = Column(String)
    investor_stage = Column(JSONB)
    investor_type = Column(JSONB)
    last_name = Column(String)
    layout_id = Column(String)
    linkedin = Column(JSONB)
    location_group_identifiers = Column(JSONB)
    location_identifiers = Column(JSONB)
    middle_name = Column(String)
    num_articles = Column(Integer)
    num_current_advisor_jobs = Column(Integer)
    num_current_jobs = Column(Integer)
    num_diversity_spotlight_investments = Column(Integer)
    num_event_appearances = Column(Integer)
    num_exits = Column(Integer)
    num_exits_ipo = Column(Integer)
    num_investments = Column(Integer)
    num_jobs = Column(Integer)
    num_lead_investments = Column(Integer)
    num_past_advisor_jobs = Column(Integer)
    num_past_jobs = Column(Integer)
    num_portfolio_organizations = Column(Integer)
    permalink = Column(String)
    permalink_aliases = Column(JSONB)
    primary_job_title = Column(String)
    primary_organization = Column(JSONB)
    rank_delta_d30 = Column(Integer)
    rank_delta_d7 = Column(Integer)
    rank_delta_d90 = Column(Integer)
    rank_person = Column(Integer)
    rank_principal = Column(Integer)
    short_description = Column(String)
    twitter = Column(JSONB)
    website_url = Column(String)

    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)


class CbQueryCache(Base):
    __tablename__ = "cb_query_cache"

    id = Column(Integer, primary_key=True, autoincrement=True)
    query_hash = Column(String, unique=True, index=True)
    search_condition = Column(String)
    items_list = Column(JSONB)
    extra_filters = Column(JSONB)
    resulting_uuids = Column(JSONB)

    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)
