"""adding model name column

Revision ID: 223e827c20cd
Revises: 0702935bb23f
Create Date: 2025-08-19 16:47:43.885331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '223e827c20cd'
down_revision: Union[str, None] = '0702935bb23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_response', sa.Column('model_name', sa.String(), nullable=True))
    op.execute("UPDATE prompt_response SET model_name = 'previously_run'")
    op.drop_constraint('prompt_response_pkey', 'prompt_response', type_='primary')
    op.create_primary_key('prompt_response_pkey', 'prompt_response', ['prompt_id', 'given_id', 'model_name'])
    op.create_index(op.f('ix_prompt_response_model_name'), 'prompt_response', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_response_model_name'), table_name='prompt_response')
    op.drop_constraint('prompt_response_pkey', 'prompt_response', type_='primary')
    op.create_primary_key('prompt_response_pkey', 'prompt_response', ['prompt_id', 'given_id'])
    op.drop_column('prompt_response', 'model_name')
