"""adding user groups column

Revision ID: 240baaf1ed96
Revises: a0acc9b5e038
Create Date: 2024-07-01 18:31:23.525188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '240baaf1ed96'
down_revision: Union[str, None] = 'a0acc9b5e038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_person', sa.Column('member_groups_collection', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_person', 'member_groups_collection')

