"""adding index to parsed websites

Revision ID: 28e94a837b5a
Revises: 6f807f876486
Create Date: 2025-04-02 09:08:02.298117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e94a837b5a'
down_revision: Union[str, None] = '6f807f876486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_web_pages_parsed_cleaned_home_key'), 'web_pages_parsed', ['cleaned_home_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_pages_parsed_cleaned_home_key'), table_name='web_pages_parsed')
    # ### end Alembic commands ###
