"""linkedin_orgs

Revision ID: 2c936a90e6dc
Revises: 4005e1076c66
Create Date: 2024-04-08 16:59:14.200968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c936a90e6dc'
down_revision: Union[str, None] = '4005e1076c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_organization', sa.Column('hq_location', sa.String(), nullable=True))
    op.drop_column('linkedin_organization', 'hq')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_organization', sa.Column('hq', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('linkedin_organization', 'hq_location')
    # ### end Alembic commands ###
