"""Rethinking id'ing

Revision ID: 3875f06f2dcb
Revises: cafe66170b77
Create Date: 2026-01-12 15:26:25.881884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3875f06f2dcb'
down_revision: Union[str, None] = 'cafe66170b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_commercial_deals_nzi',
        sa.Column('clientID', sa.Integer(), nullable=False),
        sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('date_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('clientID')
    )
    op.create_table('company_funding_rounds_nzi',
        sa.Column('clientID', sa.Integer(), nullable=False),
        sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('date_updated', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('clientID')
    )
    op.drop_table('commercial_deals_nzi')
    op.drop_table('funding_rounds_nzi')
    # Drop the existing primary key constraint on 'id' before modifying columns
    op.drop_constraint('startups_nzi_pkey', 'startups_nzi', type_='primary')
    op.alter_column('startups_nzi', 'clientID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('startups_nzi_clientID_key'), 'startups_nzi', type_='unique')
    op.drop_column('startups_nzi', 'id')
    # Create primary key constraint on 'clientID'
    op.create_primary_key('startups_nzi_pkey', 'startups_nzi', ['clientID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the primary key constraint on 'clientID' before modifying columns
    op.drop_constraint('startups_nzi_pkey', 'startups_nzi', type_='primary')
    op.add_column('startups_nzi', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # Create primary key constraint on 'id'
    op.create_primary_key('startups_nzi_pkey', 'startups_nzi', ['id'])
    op.create_unique_constraint(op.f('startups_nzi_clientID_key'), 'startups_nzi', ['clientID'], postgresql_nulls_not_distinct=False)
    op.alter_column('startups_nzi', 'clientID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('funding_rounds_nzi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dealID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clientID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('funding_rounds_nzi_pkey')),
    sa.UniqueConstraint('clientID', name=op.f('funding_rounds_nzi_clientID_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('dealID', name=op.f('funding_rounds_nzi_dealID_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('commercial_deals_nzi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clientID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('commercial_deals_nzi_pkey')),
    sa.UniqueConstraint('clientID', name=op.f('commercial_deals_nzi_clientID_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('company_funding_rounds_nzi')
    op.drop_table('company_commercial_deals_nzi')
    # ### end Alembic commands ###
