"""create nzi startup

Revision ID: 6d7b79bdecbc
Revises: d3ccdfd2c4ba
Create Date: 2025-12-12 16:34:07.336958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7b79bdecbc'
down_revision: Union[str, None] = 'd3ccdfd2c4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups_nzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clientID')
    )

    op.drop_index(op.f('idx_scraped_pages_content_hash'), table_name='scraped_pages')
    op.drop_index(op.f('idx_scraped_pages_created_at'), table_name='scraped_pages')
    op.drop_index(op.f('idx_scraped_pages_domain'), table_name='scraped_pages')
    op.drop_index(op.f('idx_scraped_pages_scraped_at'), table_name='scraped_pages')
    op.drop_table('scraped_pages')
    op.drop_index(op.f('ix_startup_funding_rounds_nzi_clientId'), table_name='startup_funding_rounds_nzi')
    op.drop_index(op.f('ix_startup_funding_rounds_nzi_fundingRoundID'), table_name='startup_funding_rounds_nzi')
    op.drop_table('startup_funding_rounds_nzi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('startups_nzi')
    # ### end Alembic commands ###
