"""creating NZI initial tables

Revision ID: 793deca41949
Revises: 18a43e1168f4
Create Date: 2025-05-15 17:20:06.352186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '793deca41949'
down_revision: Union[str, None] = '18a43e1168f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startups_nzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('alternativeNames', sa.JSON(), nullable=True),
    sa.Column('legalNames', sa.JSON(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('pitchLine', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('uniqueSellingProposition', sa.String(), nullable=True),
    sa.Column('pitchdeckURL', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('linkedinURL', sa.String(), nullable=True),
    sa.Column('twitterURL', sa.String(), nullable=True),
    sa.Column('facebookURL', sa.String(), nullable=True),
    sa.Column('directURL', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('cityID', sa.Integer(), nullable=True),
    sa.Column('admin1', sa.String(), nullable=True),
    sa.Column('admin2', sa.String(), nullable=True),
    sa.Column('admin3', sa.String(), nullable=True),
    sa.Column('admin4', sa.String(), nullable=True),
    sa.Column('admin1ID', sa.Integer(), nullable=True),
    sa.Column('admin2ID', sa.Integer(), nullable=True),
    sa.Column('admin3ID', sa.Integer(), nullable=True),
    sa.Column('admin4ID', sa.Integer(), nullable=True),
    sa.Column('georowID', sa.Integer(), nullable=True),
    sa.Column('countryID', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('countryCode', sa.String(), nullable=True),
    sa.Column('continent', sa.String(), nullable=True),
    sa.Column('continentID', sa.Integer(), nullable=True),
    sa.Column('foundedDate', sa.Integer(), nullable=True),
    sa.Column('acquisitionDate', sa.String(), nullable=True),
    sa.Column('lastRoundDate', sa.String(), nullable=True),
    sa.Column('reviewDate', sa.String(), nullable=True),
    sa.Column('lastSeenDate', sa.String(), nullable=True),
    sa.Column('dealsReviewDate', sa.DateTime(), nullable=True),
    sa.Column('trlAcquisitionDate', sa.String(), nullable=True),
    sa.Column('currentlyFundraisingDate', sa.String(), nullable=True),
    sa.Column('fundingAmount', sa.Float(), nullable=True),
    sa.Column('fundingString', sa.String(), nullable=True),
    sa.Column('fundingAmountUSD', sa.Float(), nullable=True),
    sa.Column('fundingStringUSD', sa.String(), nullable=True),
    sa.Column('fundingRangeID', sa.Integer(), nullable=True),
    sa.Column('fundingRange', sa.String(), nullable=True),
    sa.Column('fundingRangeUSD', sa.String(), nullable=True),
    sa.Column('fundingRangeIDUSD', sa.Integer(), nullable=True),
    sa.Column('lastRoundAmount', sa.BigInteger(), nullable=True),
    sa.Column('lastRoundAmountUSD', sa.BigInteger(), nullable=True),
    sa.Column('lastRoundAmountString', sa.String(), nullable=True),
    sa.Column('lastRoundAmountStringUSD', sa.String(), nullable=True),
    sa.Column('lastRoundType', sa.String(), nullable=True),
    sa.Column('roundCount', sa.Integer(), nullable=True),
    sa.Column('roundWithDateCount', sa.Integer(), nullable=True),
    sa.Column('numberOfEquityRounds', sa.Integer(), nullable=True),
    sa.Column('numberOfDebtRounds', sa.Integer(), nullable=True),
    sa.Column('numberOfGrants', sa.Integer(), nullable=True),
    sa.Column('lastPostMoneyValuation', sa.Float(), nullable=True),
    sa.Column('lastPostMoneyValuationCurrency', sa.String(), nullable=True),
    sa.Column('fundRaising', sa.Boolean(), nullable=True),
    sa.Column('isFundRaising', sa.Boolean(), nullable=True),
    sa.Column('currentlyFundraising', sa.Boolean(), nullable=True),
    sa.Column('dealsLastReviewer', sa.String(), nullable=True),
    sa.Column('revenueEuro', sa.BigInteger(), nullable=True),
    sa.Column('revenueYear', sa.Integer(), nullable=True),
    sa.Column('revenuesRangeID', sa.Integer(), nullable=True),
    sa.Column('linkedInRevenuesRangeID', sa.Integer(), nullable=True),
    sa.Column('revenuesRange', sa.String(), nullable=True),
    sa.Column('sizeID', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('stageID', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('currentEmployeesCount', sa.Integer(), nullable=True),
    sa.Column('employeesGrowthJSON', sa.String(), nullable=True),
    sa.Column('eutopiaScore', sa.Integer(), nullable=True),
    sa.Column('yoYEmployeesGrowth', sa.Float(), nullable=True),
    sa.Column('qoQEmployeesGrowth', sa.Float(), nullable=True),
    sa.Column('yoYCorrespondingQuarter', sa.String(), nullable=True),
    sa.Column('qoQCorrespondingQuarter', sa.String(), nullable=True),
    sa.Column('sustainabilityMetric', sa.Float(), nullable=True),
    sa.Column('sustainabilityMetricID', sa.Integer(), nullable=True),
    sa.Column('sustainabilityMetricLabel', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('trl', sa.JSON(), nullable=True),
    sa.Column('trlID', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('lastReviewer', sa.String(), nullable=True),
    sa.Column('intellectualProperty', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('piFrameworks', sa.JSON(), nullable=True),
    sa.Column('fundingTypes', sa.JSON(), nullable=True),
    sa.Column('sdgs', sa.JSON(), nullable=True),
    sa.Column('actorTypes', sa.JSON(), nullable=True),
    sa.Column('investorPartnerSet', sa.JSON(), nullable=True),
    sa.Column('companyContactSet', sa.JSON(), nullable=True),
    sa.Column('tbFinancialStage', sa.JSON(), nullable=True),
    sa.Column('tagSourceMap', sa.JSON(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clientID')
    )
    op.create_table('startup_funding_rounds_nzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientId', sa.Integer(), nullable=True),
    sa.Column('fundingRoundID', sa.Integer(), nullable=True),
    sa.Column('roundDate', sa.DateTime(), nullable=True),
    sa.Column('roundType', sa.String(), nullable=True),
    sa.Column('roundCurrency', sa.String(), nullable=True),
    sa.Column('roundAmount', sa.Float(), nullable=True),
    sa.Column('roundAmountUSD', sa.Float(), nullable=True),
    sa.Column('roundAmountID', sa.Integer(), nullable=True),
    sa.Column('coFundingRoundID', sa.Integer(), nullable=True),
    sa.Column('originalRoundAmount', sa.Float(), nullable=True),
    sa.Column('equityStageID', sa.Integer(), nullable=True),
    sa.Column('exitStageID', sa.Integer(), nullable=True),
    sa.Column('fundingRange', sa.String(), nullable=True),
    sa.Column('financingType', sa.String(), nullable=True),
    sa.Column('roundNewsIDs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roundInvestorIDs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roundNews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roundInvestors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valuationOriginalCurrency', sa.String(), nullable=True),
    sa.Column('valuationAmount', sa.Float(), nullable=True),
    sa.Column('valuationCurrency', sa.String(), nullable=True),
    sa.Column('valuationType', sa.String(), nullable=True),
    sa.Column('valuationAmountInOriginalCurrency', sa.Float(), nullable=True),
    sa.Column('hideValuation', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientId'], ['startups_nzi.clientID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_funding_rounds_nzi_clientId'), 'startup_funding_rounds_nzi', ['clientId'], unique=False)
    op.create_index(op.f('ix_startup_funding_rounds_nzi_fundingRoundID'), 'startup_funding_rounds_nzi', ['fundingRoundID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startup_funding_rounds_nzi_fundingRoundID'), table_name='startup_funding_rounds_nzi')
    op.drop_index(op.f('ix_startup_funding_rounds_nzi_clientId'), table_name='startup_funding_rounds_nzi')
    op.drop_table('startup_funding_rounds_nzi')
    op.drop_table('startups_nzi')
    # ### end Alembic commands ###
