"""making new table

Revision ID: 8dd63f06d7d2
Revises: d338c132c89f
Create Date: 2025-04-01 11:51:16.344624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd63f06d7d2'
down_revision: Union[str, None] = 'd338c132c89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_pages_parsed',
    sa.Column('cleaned_home_key', sa.String(), nullable=False),
    sa.Column('num_errors', sa.Integer(), nullable=True),
    sa.Column('combined_text', sa.String(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cleaned_home_key')
    )


    # op.add_column('web_pages_scraped', sa.Column('parent_key', sa.String(), nullable=False))
    # op.create_foreign_key(None, 'web_pages_scraped', 'web_pages_parsed', ['parent_key'], ['cleaned_home_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'web_pages_scraped', type_='foreignkey')
    # op.drop_column('web_pages_scraped', 'parent_key')
    op.drop_table('web_pages_parsed')
    # ### end Alembic commands ###
