"""fixing cbfuding round

Revision ID: 929daaec483f
Revises: c7e2f9a1b5d8
Create Date: 2026-03-19 16:58:36.064520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '929daaec483f'
down_revision: Union[str, None] = 'c7e2f9a1b5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cb_funding_rounds', sa.Column('identifier', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cb_funding_rounds', 'identifier')
    # ### end Alembic commands ###
