"""adding user skills column

Revision ID: a0acc9b5e038
Revises: 0ea58c3d86af
Create Date: 2024-06-28 17:49:30.449651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0acc9b5e038'
down_revision: Union[str, None] = '0ea58c3d86af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_person', sa.Column('member_skills_collection', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_person', 'member_skills_collection')
    # ### end Alembic commands ###
