"""adding cascade

Revision ID: aaabae0f8808
Revises: 158d33a016fe
Create Date: 2024-04-29 16:55:40.836251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaabae0f8808'
down_revision: Union[str, None] = '158d33a016fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prompt_response_prompt_id_fkey', 'prompt_response', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_response', 'prompt', ['prompt_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_response', type_='foreignkey')
    op.create_foreign_key('prompt_response_prompt_id_fkey', 'prompt_response', 'prompt', ['prompt_id'], ['id'])
    # ### end Alembic commands ###
