"""NZI fundingrounds table

Revision ID: cafe66170b77
Revises: db9ab83338c7
Create Date: 2026-01-09 14:45:43.109418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cafe66170b77'
down_revision: Union[str, None] = 'db9ab83338c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_rounds_nzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dealID', sa.Integer(), nullable=True),
    sa.Column('clientID', sa.Integer(), nullable=True),
    sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clientID'),
    sa.UniqueConstraint('dealID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_rounds_nzi')
    # ### end Alembic commands ###
