"""adding coresignal id column

Revision ID: d338c132c89f
Revises: cbd7c32798d8
Create Date: 2024-08-01 15:35:49.078558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd338c132c89f'
down_revision: Union[str, None] = 'cbd7c32798d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_organization', sa.Column('coresignal_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_organization', 'coresignal_id')
    # ### end Alembic commands ###
