"""add_linkedin_employee_base_and_clean_tables

Revision ID: d3ccdfd2c4ba
Revises: 223e827c20cd
Create Date: 2025-11-03 10:18:34.807452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3ccdfd2c4ba'
down_revision: Union[str, None] = '223e827c20cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_base_employee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('is_parent', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('public_profile_id', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('services', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_iso_2', sa.String(), nullable=True),
    sa.Column('country_iso_3', sa.String(), nullable=True),
    sa.Column('recommendations_count', sa.Integer(), nullable=True),
    sa.Column('connections_count', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('experience_count', sa.Integer(), nullable=True),
    sa.Column('shorthand_name', sa.String(), nullable=False),
    sa.Column('canonical_shorthand_name', sa.String(), nullable=False),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shorthand_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('historical_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('also_viewed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('courses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organizations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('posts_see_more_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('similar_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('others_named', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('test_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('volunteering_cares', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('volunteering_opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('volunteering_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('volunteering_supports', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('websites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('course_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('activity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hidden_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_base_employee_original_url'), 'linkedin_base_employee', ['original_url'], unique=False)
    op.create_index(op.f('ix_linkedin_base_employee_profile_url'), 'linkedin_base_employee', ['profile_url'], unique=False)
    op.create_table('linkedin_clean_employee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('public_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('name_first', sa.String(), nullable=True),
    sa.Column('name_middle', sa.String(), nullable=True),
    sa.Column('name_last', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('generated_headline', sa.String(), nullable=True),
    sa.Column('websites_linkedin', sa.String(), nullable=True),
    sa.Column('shorthand_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('is_hidden', sa.Integer(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location_raw_address', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('location_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('connections_count', sa.Integer(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('is_working', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('management_level', sa.String(), nullable=True),
    sa.Column('is_decision_maker', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('total_experience_duration', sa.String(), nullable=True),
    sa.Column('total_experience_duration_months', sa.Integer(), nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations_count', sa.Integer(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('courses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organizations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('full_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_clean_employee_company_id'), 'linkedin_clean_employee', ['company_id'], unique=False)
    op.create_index(op.f('ix_linkedin_clean_employee_original_url'), 'linkedin_clean_employee', ['original_url'], unique=False)
    op.create_index(op.f('ix_linkedin_clean_employee_websites_linkedin'), 'linkedin_clean_employee', ['websites_linkedin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_clean_employee_websites_linkedin'), table_name='linkedin_clean_employee')
    op.drop_index(op.f('ix_linkedin_clean_employee_original_url'), table_name='linkedin_clean_employee')
    op.drop_index(op.f('ix_linkedin_clean_employee_company_id'), table_name='linkedin_clean_employee')
    op.drop_table('linkedin_clean_employee')
    op.drop_index(op.f('ix_linkedin_base_employee_profile_url'), table_name='linkedin_base_employee')
    op.drop_index(op.f('ix_linkedin_base_employee_original_url'), table_name='linkedin_base_employee')
    op.drop_table('linkedin_base_employee')
    # ### end Alembic commands ###
