"""create nzi commercial_deals_table

Revision ID: db9ab83338c7
Revises: 6d7b79bdecbc
Create Date: 2025-12-17 12:18:17.629174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db9ab83338c7'
down_revision: Union[str, None] = '6d7b79bdecbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial_deals_nzi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=True),
    sa.Column('fullData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clientID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commercial_deals_nzi')
    # ### end Alembic commands ###
