import re


USPS_MAP = {
    # --- STREET SUFFIXES ---
    'ALLEY': 'ALY', 'ALY': 'ALY',
    'ANNEX': 'ANX', 'ANX': 'ANX',
    'ARCADE': 'ARC', 'ARC': 'ARC',
    'AVENUE': 'AVE', 'AVE': 'AVE',
    'BAYOO': 'BYU', 'BAYOU': 'BYU',
    'BEACH': 'BCH', 'BCH': 'BCH',
    'BEND': 'BND', 'BND': 'BND',
    'BLUFF': 'BLF', 'BLFS': 'BLF', 'BLF': 'BLF',
    'BOTTOM': 'BTM', 'BOT': 'BTM', 'BTM': 'BTM',
    'BOULEVARD': 'BLVD', 'BLVD': 'BLVD',
    'BRANCH': 'BR', 'BR': 'BR',
    'BRIDGE': 'BRG', 'BRG': 'BRG',
    'BROOK': 'BRK', 'BRK': 'BRK',
    'BURG': 'BG', 'BG': 'BG',
    'BYPASS': 'BYP', 'BYP': 'BYP',
    'CAMP': 'CP', 'CP': 'CP',
    'CANYON': 'CYN', 'CYN': 'CYN',
    'CAPE': 'CPE', 'CPE': 'CPE',
    'CAUSEWAY': 'CSWY', 'CSWY': 'CSWY',
    'CENTER': 'CTR', 'CEN': 'CTR', 'CTR': 'CTR',
    'CIRCLE': 'CIR', 'CIR': 'CIR', 'CIRCL': 'CIR', 'CRCL': 'CIR',
    'CLIFF': 'CLF', 'CLFS': 'CLF', 'CLF': 'CLF',
    'CLUB': 'CLB', 'CLB': 'CLB',
    'COMMON': 'CMN', 'COMMONS': 'CMN',
    'CORNER': 'COR', 'CORNERS': 'COR', 'COR': 'COR',
    'COURSE': 'CRSE', 'CRSE': 'CRSE',
    'COURT': 'CT', 'CT': 'CT',
    'COVE': 'CV', 'CV': 'CV',
    'CREEK': 'CRK', 'CRK': 'CRK',
    'CRESCENT': 'CRES', 'CRES': 'CRES', 'CRSENT': 'CRES',
    'CROSSING': 'XING', 'XING': 'XING',
    'DALE': 'DL', 'DL': 'DL',
    'DAM': 'DM', 'DM': 'DM',
    'DIVIDE': 'DV', 'DIV': 'DV', 'DV': 'DV',
    'DRIVE': 'DR', 'DR': 'DR', 'DRIV': 'DR',
    'ESTATE': 'EST', 'ESTATES': 'EST', 'EST': 'EST',
    'EXPRESSWAY': 'EXPY', 'EXP': 'EXPY', 'EXPWY': 'EXPY', 'EXPY': 'EXPY',
    'EXTENSION': 'EXT', 'EXT': 'EXT',
    'FALL': 'FALL', 'FALLS': 'FLS', 'FLS': 'FLS',
    'FERRY': 'FRY', 'FRY': 'FRY',
    'FIELD': 'FLD', 'FIELDS': 'FLDS', 'FLD': 'FLD',
    'FLAT': 'FLT', 'FLATS': 'FLT', 'FLT': 'FLT',
    'FORD': 'FRD', 'FRD': 'FRD',
    'FOREST': 'FRST', 'FRST': 'FRST',
    'FORGE': 'FRG', 'FRG': 'FRG',
    'FORK': 'FRK', 'FORKS': 'FRK', 'FRK': 'FRK',
    'FORT': 'FT', 'FT': 'FT',
    'FREEWAY': 'FWY', 'FREEWY': 'FWY', 'FWY': 'FWY',
    'GARDEN': 'GDN', 'GARDENS': 'GDNS', 'GDN': 'GDN',
    'GATEWAY': 'GTWY', 'GATEWY': 'GTWY', 'GATWAY': 'GTWY', 'GTWY': 'GTWY',
    'GLEN': 'GLN', 'GLN': 'GLN',
    'GREEN': 'GRN', 'GREENS': 'GRNS', 'GRN': 'GRN',
    'GROVE': 'GRV', 'GROV': 'GRV', 'GRV': 'GRV',
    'HARBOR': 'HBR', 'HARB': 'HBR', 'HBR': 'HBR',
    'HAVEN': 'HVN', 'HVN': 'HVN',
    'HEIGHTS': 'HTS', 'HT': 'HTS', 'HTS': 'HTS',
    'HIGHWAY': 'HWY', 'HIGHWY': 'HWY', 'HIWAY': 'HWY', 'HWAY': 'HWY', 'HWY': 'HWY',
    'HILL': 'HL', 'HILLS': 'HLS', 'HL': 'HL',
    'HOLLOW': 'HOLW', 'HOLLOWS': 'HOLW', 'HOLW': 'HOLW',
    'INLET': 'INLT', 'INLT': 'INLT',
    'ISLAND': 'IS', 'ISLANDS': 'ISS', 'IS': 'IS',
    'ISLE': 'ISLE',
    'JUNCTION': 'JCT', 'JCT': 'JCT', 'JCTION': 'JCT',
    'KEY': 'KY', 'KEYS': 'KYS', 'KY': 'KY',
    'KNOLL': 'KNL', 'KNOLLS': 'KNLS', 'KNL': 'KNL',
    'LAKE': 'LK', 'LAKES': 'LKS', 'LK': 'LK',
    'LANDING': 'LNDG', 'LNDG': 'LNDG',
    'LANE': 'LN', 'LN': 'LN',
    'LIGHT': 'LGT', 'LIGHTS': 'LGTS', 'LGT': 'LGT',
    'LOAF': 'LF', 'LF': 'LF',
    'LOCK': 'LCK', 'LOCKS': 'LCKS', 'LCK': 'LCK',
    'LODGE': 'LDG', 'LDG': 'LDG',
    'LOOP': 'LOOP', 'LOOPS': 'LOOP',
    'MALL': 'MALL',
    'MANOR': 'MNR', 'MANORS': 'MNRS', 'MNR': 'MNR',
    'MEADOW': 'MDW', 'MEADOWS': 'MDWS', 'MDW': 'MDW',
    'MEWS': 'MEWS',
    'MILL': 'ML', 'MILLS': 'MLS', 'ML': 'ML',
    'MISSION': 'MSN', 'MISSN': 'MSN', 'MSSN': 'MSN', 'MSN': 'MSN',
    'MOTORWAY': 'MTWY', 'MTWY': 'MTWY',
    'MOUNT': 'MT', 'MNT': 'MT', 'MT': 'MT',
    'MOUNTAIN': 'MTN', 'MNTAIN': 'MTN', 'MNTN': 'MTN', 'MOUNTIN': 'MTN', 'MTIN': 'MTN', 'MTN': 'MTN',
    'NECK': 'NCK', 'NCK': 'NCK',
    'ORCHARD': 'ORCH', 'ORCH': 'ORCH',
    'OVAL': 'OVAL', 'OVL': 'OVAL',
    'PARK': 'PARK', 'PRK': 'PARK', 'PARKS': 'PARK',
    'PARKWAY': 'PKWY', 'PARKWY': 'PKWY', 'PKWAY': 'PKWY', 'PKY': 'PKWY', 'PKWY': 'PKWY',
    'PASS': 'PASS',
    'PASSAGE': 'PSGE', 'PSGE': 'PSGE',
    'PATH': 'PATH', 'PATHS': 'PATH',
    'PIKE': 'PIKE', 'PIKES': 'PIKE',
    'PINE': 'PNE', 'PINES': 'PNES', 'PNE': 'PNE',
    'PLACE': 'PL', 'PL': 'PL',
    'PLAIN': 'PLN', 'PLAINS': 'PLNS', 'PLN': 'PLN',
    'PLAZA': 'PLZ', 'PLZA': 'PLZ', 'PLZ': 'PLZ',
    'POINT': 'PT', 'POINTS': 'PTS', 'PT': 'PT',
    'PORT': 'PRT', 'PORTS': 'PRTS', 'PRT': 'PRT',
    'PRAIRIE': 'PR', 'PR': 'PR',
    'RADIAL': 'RADL', 'RAD': 'RADL', 'RADL': 'RADL',
    'RAMP': 'RAMP',
    'RANCH': 'RNCH', 'RANCHES': 'RNCH', 'RNCH': 'RNCH',
    'RAPID': 'RPD', 'RAPIDS': 'RPDS', 'RPD': 'RPD',
    'REST': 'RST', 'RST': 'RST',
    'RIDGE': 'RDG', 'RIDGES': 'RDGS', 'RDG': 'RDG',
    'RIVER': 'RIV', 'RVR': 'RIV', 'RIV': 'RIV',
    'ROAD': 'RD', 'RD': 'RD',
    'ROUTE': 'RTE', 'RTE': 'RTE',
    'ROW': 'ROW',
    'RUN': 'RUN',
    'SHOAL': 'SHL', 'SHOALS': 'SHLS', 'SHL': 'SHL',
    'SHORE': 'SHR', 'SHORES': 'SHRS', 'SHR': 'SHR',
    'SKYWAY': 'SKWY', 'SKWY': 'SKWY',
    'SPRING': 'SPG', 'SPRINGS': 'SPGS', 'SPG': 'SPG', 'SPNG': 'SPG',
    'SPUR': 'SPUR', 'SPURS': 'SPUR',
    'SQUARE': 'SQ', 'SQUARES': 'SQS', 'SQR': 'SQ', 'SQRE': 'SQ', 'SQ': 'SQ',
    'STATION': 'STA', 'STATN': 'STA', 'STN': 'STA', 'STA': 'STA',
    'STRAVENUE': 'STRA', 'STRA': 'STRA',
    'STREAM': 'STRM', 'STRM': 'STRM',
    'STREET': 'ST', 'STRT': 'ST', 'STR': 'ST', 'ST': 'ST',
    'SUMMIT': 'SMT', 'SUMIT': 'SMT', 'SUMITT': 'SMT', 'SMT': 'SMT',
    'TERRACE': 'TER', 'TERR': 'TER', 'TER': 'TER',
    'THROUGHWAY': 'TRWY', 'TRWY': 'TRWY',
    'TRACE': 'TRCE', 'TRACE': 'TRCE', 'TRCE': 'TRCE',
    'TRACK': 'TRAK', 'TRACKS': 'TRAK', 'TRK': 'TRAK', 'TRAK': 'TRAK',
    'TRAFFICWAY': 'TRFY', 'TRFY': 'TRFY',
    'TRAIL': 'TRL', 'TRAILS': 'TRL', 'TRLS': 'TRL', 'TRL': 'TRL',
    'TRAILER': 'TRLR', 'TRLR': 'TRLR',
    'TUNNEL': 'TUNL', 'TUNLS': 'TUNL', 'TUNL': 'TUNL',
    'TURNPIKE': 'TPKE', 'TRNPK': 'TPKE', 'TURNPK': 'TPKE', 'TPKE': 'TPKE',
    'UNDERPASS': 'UPAS', 'UPAS': 'UPAS',
    'UNION': 'UN', 'UNIONS': 'UNS', 'UN': 'UN',
    'VALLEY': 'VLY', 'VALLEYS': 'VLYS', 'VLLY': 'VLY', 'VLY': 'VLY',
    'VIADUCT': 'VIA', 'VDCT': 'VIA', 'VIA': 'VIA',
    'VIEW': 'VW', 'VIEWS': 'VWS', 'VW': 'VW',
    'VILLAGE': 'VLG', 'VILL': 'VLG', 'VILLG': 'VLG', 'VLG': 'VLG',
    'VILLE': 'VL', 'VL': 'VL',
    'VISTA': 'VIS', 'VIST': 'VIS', 'VST': 'VIS', 'VIS': 'VIS',
    'WALK': 'WALK', 'WALKS': 'WALK',
    'WAY': 'WAY',
    'WELL': 'WL', 'WELLS': 'WLS', 'WL': 'WL',

    # --- SECONDARY UNIT DESIGNATORS ---
    'APARTMENT': 'APT', 'APMT': 'APT', 'APT': 'APT',
    'BASEMENT': 'BSMT', 'BSMT': 'BSMT',
    'BUILDING': 'BLDG', 'BLDG': 'BLDG',
    'DEPARTMENT': 'DEPT', 'DEPT': 'DEPT',
    'FLOOR': 'FL', 'FLR': 'FL', 'FL': 'FL',
    'FRONT': 'FRNT', 'FRNT': 'FRNT',
    'HANGAR': 'HNGR', 'HNGR': 'HNGR',
    'LOBBY': 'LBBY', 'LOBBY': 'LBBY',
    'LOT': 'LOT',
    'LOWER': 'LOWR', 'LOWR': 'LOWR',
    'OFFICE': 'OFC', 'OFC': 'OFC',
    'PENTHOUSE': 'PH', 'PH': 'PH',
    'PIER': 'PIER',
    'REAR': 'REAR',
    'ROOM': 'RM', 'RM': 'RM',
    'SIDE': 'SIDE',
    'SLIP': 'SLIP',
    'SPACE': 'SPC', 'SPC': 'SPC',
    'STOP': 'STOP',
    'SUITE': 'STE', 'SUIT': 'STE', 'STE': 'STE',
    'TRAILER': 'TRLR', 'TRLR': 'TRLR',
    'UNIT': 'UNIT', 'UNT': 'UNIT',
    'UPPER': 'UPPR', 'UPPR': 'UPPR',

    # --- DIRECTIONALS ---
    'NORTH': 'N', 'N': 'N',
    'SOUTH': 'S', 'S': 'S',
    'EAST': 'E', 'E': 'E',
    'WEST': 'W', 'W': 'W',
    'NORTHEAST': 'NE', 'NE': 'NE',
    'NORTHWEST': 'NW', 'NW': 'NW',
    'SOUTHEAST': 'SE', 'SE': 'SE',
    'SOUTHWEST': 'SW', 'SW': 'SW',
}

USPS_KEYS = sorted(USPS_MAP.keys(), key=len, reverse=True)
# Create a pattern like: \b(STREET|AVENUE|...)\b
ADDRESS_PATTERN = re.compile(r'\b(' + '|'.join(re.escape(k) for k in USPS_KEYS) + r')\b\.?', re.IGNORECASE)


def create_clean_address(
    row,
    address_part_columns=['address1_key', 'address2_key', 'addresscity_key', 'addressstate_key']
):
    parts = [row[col] for col in address_part_columns]
    name = " ".join([p.strip() for p in parts if p.strip()])

    if not isinstance(name, str):
        return ""

    # 1. Uppercase & Strip
    name = name.upper().strip()

    # 2. Apply the Master Regex
    # This looks up the match in the dictionary and replaces it
    name = ADDRESS_PATTERN.sub(lambda x: USPS_MAP[x.group().upper().replace('.', '')], name)

    # 3. Clean up Punctuation (remove commas/dots that remained)
    name = re.sub(r'[^\w\s]', '', name)

    # 4. Remove double spaces
    name = re.sub(r'\s+', ' ', name).strip()
    return name
